blog/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from posts.views import RegisterFormView, UpdateProfile


urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('', RedirectView.as_view(url='posts/', permanent=True)),

    # Add Django site authentication urls (for login, logout, password management)
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', RegisterFormView.as_view(), name='register'),
    path('accounts/update_profile/', UpdateProfile.as_view(), name='update_profile'),
]

urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]

posts/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from . import views


app_name = 'posts'
urlpatterns = [
    path('', cache_page(1000)(views.index), name='index'),
    path('posts/create/', views.PostCreate.as_view(), name='post_create'),
    path('posts/update/<int:pk>/', views.PostUpdate.as_view(), name='post_update'),
    path('posts/delete/<int:pk>/', views.PostDelete.as_view(), name='post_delete'),
    path('posts/', cache_page(5)(views.PostList.as_view()), name='post_list'),
    path('posts/<int:pk>/', cache_page(10)(views.post_detail), name='post_detail'),
    path('my-posts/', views.users_posts, name='users_posts'),
    path('user/<int:pk>', cache_page(15)(views.user_detail), name='user_detail'),
    path('user/', cache_page(5)(views.UserList.as_view()), name='user_list'),
    path('feedback', views.feedback_form, name="feedback"),
    path('rss-posts', views.RSSPostList.as_view(), name="rss_post_list"),
]

posts/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _


# Create your models here.
class Post(models.Model):
    title = models.CharField(_("title"), max_length=100)
    short_description = models.CharField(_("short description"), max_length=200)
    image = models.URLField(max_length=400)
    full_description = models.TextField(_("full description"), blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    posted = models.BooleanField(_('posted'), default=False)

    def __str__(self):
        return self.title


class Comment(models.Model):
    username = models.CharField(_("username"), max_length=100)
    text = models.CharField(_("text"), max_length=300)
    post = models.ForeignKey(Post, on_delete=models.SET_NULL, null=True)
    moderated = models.BooleanField(_('moderated'), default=False)

    def __str__(self):
        return self.username


class RSSPost(models.Model):
    title = models.CharField(_("title"), max_length=300)
    link = models.URLField(max_length=400)

    def __str__(self):
        return self.title

posts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Comment


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['username', 'text']


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class FeedbackFrom(forms.Form):
    email = forms.EmailField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

posts/views.py
from django.contrib.auth import authenticate, get_user_model, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import send_mail
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView, FormView, ListView, UpdateView

from .forms import CommentForm, FeedbackFrom, RegisterForm
from .models import Comment, Post, RSSPost

User = get_user_model()


def index(request):
    """View function for home page of site."""

    return render(request, 'posts/index.html')


class RegisterFormView(SuccessMessageMixin, FormView):
    template_name = 'registration/register.html'
    form_class = RegisterForm
    success_url = reverse_lazy('posts:index')
    success_message = 'Profile created'

    def form_valid(self, form):
        form.save()

        username = self.request.POST['username']
        password = self.request.POST['password1']

        user = authenticate(username=username, password=password)
        login(self.request, user)
        return super(RegisterFormView, self).form_valid(form)


class UpdateProfile(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ['first_name', 'last_name', 'email']
    template_name = 'registration/update_profile.html'
    success_url = reverse_lazy('posts:index')
    success_message = 'Profile updated'

    def get_object(self, queryset=None):
        user = self.request.user
        return user


class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'short_description', 'image', 'full_description', 'posted']
    template_name = 'posts/post_create_page.html'
    success_url = reverse_lazy('posts:post_list')

    def get_form_kwargs(self):
        kwargs = super(PostCreate, self).get_form_kwargs()
        if kwargs['instance'] is None:
            kwargs['instance'] = Post()
        kwargs['instance'].user = self.request.user
        return kwargs


class PostList(ListView):
    model = Post
    paginate_by = 10
    template_name = 'posts/post_list_page.html'

    def get_queryset(self):
        return Post.objects.all().filter(posted=True)


# paginator!
def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk, posted=True)
    comments = Comment.objects.all().filter(post=post).filter(moderated=True)
    paginator = Paginator(comments, 2)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    if request.method == 'POST':

        form = CommentForm(request.POST)

        if form.is_valid():
            comm = Comment()
            comm.username = form.cleaned_data['username']
            comm.text = form.cleaned_data['text']
            comm.post = post
            comm.save()
            return HttpResponseRedirect(reverse('posts:post_detail', args=(post.id,)))

    else:
        initial = {'username': request.user.username}
        form = CommentForm(initial=initial)

    context = {
        'form': form,
        'post': post,
        'page_obj': page_obj,
    }

    return render(request, 'posts/post_detail_page.html', context)


def users_posts(request):
    current_user = request.user

    posted_posts = Post.objects.filter(user=current_user).filter(posted=True)
    paginator = Paginator(posted_posts, 2)
    page_number = request.GET.get('page')
    page_obj_posted = paginator.get_page(page_number)

    unposted_posts = Post.objects.filter(user=current_user).filter(posted=False)
    paginator = Paginator(unposted_posts, 2)
    page_number = request.GET.get('page')
    page_obj_unposted = paginator.get_page(page_number)

    context = {
        'page_obj_posted': page_obj_posted,
        'page_obj_unposted': page_obj_unposted,
    }
    return render(request, 'posts/users_posts_page.html', context)


class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    template_name = 'posts/post_update_page.html'
    fields = ['title', 'short_description', 'image', 'full_description', 'posted']
    success_url = reverse_lazy('posts:post_list')

    def get_object(self, queryset=None):
        obj = super(PostUpdate, self).get_object()
        if not obj.user == self.request.user:
            return redirect(obj)
        return obj


class PostDelete(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('posts:post_list')
    template_name = 'posts/post_delete_page.html'

    def get_object(self, queryset=None):
        obj = super(PostDelete, self).get_object()
        if not obj.user == self.request.user:
            return redirect(obj)
        return obj


# paginator!
def user_detail(request, pk):
    user = get_object_or_404(User, pk=pk, is_staff=False)
    posts = Post.objects.filter(user=user).filter(posted=True)
    paginator = Paginator(posts, 5)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'obj': user,
    }
    return render(request, 'posts/user_detail_page.html', context)


class UserList(ListView):
    model = User
    template_name = 'posts/user_list_page.html'
    paginate_by = 10

    def get_queryset(self):
        return User.objects.filter(is_staff=False)


def feedback_form(request):
    if request.method == "GET":
        form = FeedbackFrom()
    else:
        form = FeedbackFrom(request.POST)
        if form.is_valid():
            subject = 'New feedback!'
            from_email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            send_mail(subject, message, from_email, ['admin@example.com'])

            return redirect('posts:feedback')
    return render(
        request,
        "posts/feedback_page.html",
        context={
            "form": form,
        }
    )


class RSSPostList(ListView):
    model = RSSPost
    template_name = 'posts/rss_post_list_page.html'
    paginate_by = 10

templates/posts/feedback_page.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Contact Us</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="form-actions">
      <button type="submit">Send</button>
    </div>
  </form>
{% endblock %}

templates/posts/index.html
{% extends "base_generic.html" %}
{% block title %}<title>Posts</title>{% endblock %}
{% block content %}
  <h1>Welcome to the club!!!</h1>
  <h3>Discover this website!</h3>
  <h4>Here you can find great popularity, write your own interesting posts, receive comments and have a lot of views.</h4>
{% endblock %}

templates/posts/post_create_page.html
{% extends "base_generic.html" %}

{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}

templates/posts/post_delete_page.html
{% extends "base_generic.html" %}

{% block content %}

<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

{% endblock %}

templates/posts/post_detail_page.html
{% extends "base_generic.html" %}

{% block content %}

<h3>Title: {{ post.title }} {{ student.last_name }}</h3></li>
<img alt="Qries" src="{{ post.image }}" width="30%">
<h5>Description: {{ post.full_description }}</h5>
<h5>Author: <a href="{% url 'posts:user_detail' post.user.id %}" >{{ post.user }}</a><h5>
<hr>
<h3>Comments</h3>
{% for comment in page_obj %}
<h6>User name:{{ comment.username }}</h6>
<h6>Comment: {{ comment.text }}</h6>
{% endfor %}

{% include "paginator_incl.html" %}
<hr>
<form method="post">
  {% csrf_token %}
  {{form.as_p}}
  <div class="form-actions">
    <button type="submit" class="btn btn-dark">Add comment</button>
  </div>
</form>

{% endblock %}

templates/posts/post_list_page.html
{% extends "base_generic.html" %}

{% block content %}

<h3>Posts:</h3>
<ul>
{% for post in page_obj %}
    <li><h4>Title: <a href="{% url 'posts:post_detail' post.id %}">{{ post.title }}</a> </h4></li>
    <h5>Short description: {{ post.short_description }} </h5>
    <h5>Author: <a href="{% url 'posts:user_detail' post.user.id %}" >{{ post.user }}</a></h5>
   	<img alt="Qries" src="{{ post.image }}" width="30%">
{% empty %}
    <li>No posts yet.</li>
{% endfor %}
</ul>
{% endblock %}

templates/posts/post_update_page.html
{% extends "base_generic.html" %}

{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}

templates/posts/rss_post_list_page.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Here we have interesting posts for you!</h1>
<h1>We hope you enjoy it!</h1>
<h3>Posts:</h3>
<ul>
{% for post in page_obj %}
    <li><h4>Title: {{ post.title }}</a> </h4></li>
    <h5>Link: <a href='{{post.link}}'>{{ post.link }}</a></h5>
   	<hr>
{% empty %}
    <li>No posts yet.</li>
{% endfor %}
</ul>
{% endblock %}

templates/posts/user_detail_page.html
{% extends "base_generic.html" %}

{% block content %}
<h2>User info: </h2>
<h5>Username: {{ obj.username }}</h5>
{% if obj.first_name and obj.last_name %}
<h5>First name: {{ obj.first_name }}</h5>
<h5>Last name: {{ obj.last_name }}</h5>
{% endif %}
<h5>Email: {{ obj.email }}</h5>
<hr>
<h2>User's posts:</h2>
<ul>
{% for post in page_obj %}
    <li><h4>Title: <a href="{% url 'posts:post_detail' post.id %}">{{ post.title }}</a> </h4></li>
    <h5>Short description: {{ post.short_description }} </h5>
   	<img alt="Qries" src="{{ post.image }}" width="30%">
{% empty %}
    <li>No posts yet.</li>
{% endfor %}
</ul>
{% include "paginator_incl.html" %}

{% endblock %}

templates/posts/user_list_page.html
{% extends "base_generic.html" %}

{% block content %}

<h3>Users:</h3>
<ul>
{% for user in page_obj %}
    <h4>User: <a href="{% url 'posts:user_detail' user.id %}">{{ user.username }}</a> </h4>
{% empty %}
    <li>No users yet.</li>
{% endfor %}
</ul>

{% endblock %}

templates/posts/users_posts_page.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Posted!</h1>
{% for post in page_obj_posted %}
  <li><h4>Title: <a href="{% url 'posts:post_detail' post.id %}">{{ post.title }}</a> </h4></li>
  <h5>Short description: {{ post.short_description }} </h5>
  <img alt="Qries" src="{{ post.image }}" width="30%">
<div>
 <a href='{% url "posts:post_update" post.id %}'>Update</a>
 <a href='{% url "posts:post_delete" post.id %}'>Delete</a>
</div>
{% empty %}
  <h3>No unposted posts yet!</h3>
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj_posted.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj_posted.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj_posted.number }} of {{ page_obj_posted.paginator.num_pages }}.
        </span>

        {% if page_obj_posted.has_next %}
            <a href="?page={{ page_obj_posted.next_page_number }}">next</a>
            <a href="?page={{ page_obj_posted.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

<hr>
<h1>Unposted!</h1>
{% for post in page_obj_unposted %}
  <li><h4>Title: {{ post.title }} </h4></li>
  <h5>Short description: {{ post.short_description }} </h5>
  <img alt="Qries" src="{{ post.image }}" width="30%">
<div>
 <a href='{% url "posts:post_update" post.id %}'>Update</a>
 <a href='{% url "posts:post_delete" post.id %}'>Delete</a>
</div>
{% empty %}
  <h3>No unposted posts yet!</h3>
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj_unposted.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj_unposted.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj_unposted.number }} of {{ page_obj_unposted.paginator.num_pages }}.
        </span>

        {% if page_obj_unposted.has_next %}
            <a href="?page={{ page_obj_unposted.next_page_number }}">next</a>
            <a href="?page={{ page_obj_unposted.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock %}