blog/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from posts.views import RegisterFormView, UpdateProfile


urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('', RedirectView.as_view(url='posts/', permanent=True)),

    # Add Django site authentication urls (for login, logout, password management)
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', RegisterFormView.as_view(), name='register'),
    path('accounts/update_profile/', UpdateProfile.as_view(), name='update_profile'),
]

urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]

posts/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from . import views


app_name = 'posts'
urlpatterns = [
    path('', cache_page(1000)(views.index), name='index'),
    path('posts/create/', views.PostCreate.as_view(), name='post_create'),
    path('posts/update/<int:pk>/', views.PostUpdate.as_view(), name='post_update'),
    path('posts/delete/<int:pk>/', views.PostDelete.as_view(), name='post_delete'),
    path('posts/', cache_page(5)(views.PostList.as_view()), name='post_list'),
    path('posts/<int:pk>/', cache_page(10)(views.post_detail), name='post_detail'),
    path('my-posts/', views.users_posts, name='users_posts'),
    path('user/<int:pk>', cache_page(15)(views.user_detail), name='user_detail'),
    path('user/', cache_page(5)(views.UserList.as_view()), name='user_list'),
    path('feedback', views.feedback_form, name="feedback"),
    path('rss-posts', views.RSSPostList.as_view(), name="rss_post_list"),
]

templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
            <li><a href="{% url 'posts:index' %}">Home</a></li>
            <li><a href="{% url 'posts:post_list' %}">All posts</a></li>
            <li><a href="{% url 'posts:user_list' %}">All users</a></li>
            <li><a href="{% url 'posts:rss_post_list' %}">Interesting posts</a></li>
        </ul>
        {% if user.is_authenticated %}
        <hr />

        <ul class="sidebar-nav">

            <li><a href="{% url 'posts:users_posts' %}">My posts</a></li>
            <li><a href="{% url 'posts:post_create' %}">Create post</a></li>
        </ul>
        {% endif %}
        <hr />

        <ul class="sidebar-nav">
            <li><a href="{% url 'posts:feedback' %}">Feedback</a></li>
        </ul>

        <hr />

        <ul class="sidebar-nav">
            {% if user.is_authenticated %}
            <li>User: {{ user.get_username }}</li>
            <li><a href="{% url 'update_profile' %}">Update profile</a></li>
            <li><a href="{% url 'logout' %}?next={{request.path}}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'login' %}?next={{request.path}}">Login</a></li>
            <li><a href="{% url 'register' %}">Register</a></li>
            {% endif %}
        </ul>

      {% endblock %}
      </div>
      <div class="col-sm-10 ">
          {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                        <strong>{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %} Error
                                {% else %}
                                {{ message.tags|title }}
                                {% endif %}!
                        </strong>
                        {{ message }}
                    </div>
                {% endfor %}
            </ul>
          {% endif %}

          {% block content %}{% endblock %}

        {% block pagination %}
          {% if is_paginated %}
            <div class="pagination">
              <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
              </span>
            </div>
          {% endif %}
        {% endblock %}


        </div>
    </div>
  </div>
</body>
</html>

templates/paginator_incl.html
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>